ops:
  copy_db_schema_2:
    ops:
      check_params_and_defaults:
        config:
          use_db: target_db
resources:
  source_db:
    config:
      host:
        env: "MY_TEST_HOST"
      port:
        env: "MY_TEST_PORT"
  target_db:
    config:
      host: myTARGEThost
      port: myTARGETport
